name: Deploy to Production Environment

on:
  push:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
      
    - name: Build for production environment
      run: npm run build:prod
      env:
        GATSBY_ENVIRONMENT: prod
        NODE_ENV: production
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Deploy to S3 Production bucket
      run: |
        aws s3 sync public/ s3://abdillamit-site-prod --delete --exact-timestamps
        
    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_PROD_DISTRIBUTION_ID }} --paths "/*"
        
    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "🚀 Production deployment successful!"
        else
          echo "❌ Production deployment failed!"
        fi

